-- Realtime risk flags generated by the stream processor
CREATE TABLE IF NOT EXISTS risk_flags (
  event_id     UUID PRIMARY KEY,                            -- deterministic ID (uuid5) to dedupe
  account_id   UUID NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  window_start TIMESTAMPTZ NOT NULL,
  window_end   TIMESTAMPTZ NOT NULL,
  count_5m     INTEGER NOT NULL,
  sum_5m       NUMERIC(20,6) NOT NULL,
  reason       TEXT NOT NULL CHECK (reason IN ('VELOCITY_COUNT','VELOCITY_SUM')),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_risk_flags_created ON risk_flags(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_risk_flags_acct_window ON risk_flags(account_id, window_end);
